using Sitecore.Data;
#pragma warning disable 1591
#pragma warning disable 0108
// ReSharper disable InconsistentNaming
// ReSharper disable MemberHidesStaticFromOuterClass
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Elision.Feature.Template.Accordion.SC.Integration
{
	public partial struct Templates
    {
        /// <summary>
        /// <list type="table">
        ///     <item><term>Template ID:</term><description>{0D0A61D7-663D-4287-9F01-E1B686E2CF8A}</description></item>
        ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Feature/ElisionFeatureTemplateAccordion/Base/_HeadingText</description></item>
        /// </list>
        /// </summary>
        public struct _HeadingText
        {
            public static readonly ID TemplateId = new ID("{0D0A61D7-663D-4287-9F01-E1B686E2CF8A}");
            public const string Name = "_HeadingText";

            public struct FieldIds
            {
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Single-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{3A413749-C918-4508-AAD9-78EF521A8E89}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Feature/ElisionFeatureTemplateAccordion/Base/_HeadingText/Data/HeadingText</description></item>
                /// </list>
                /// </summary>
                public static readonly ID HeadingText = new ID("{3A413749-C918-4508-AAD9-78EF521A8E89}");
            }

            public struct FieldNames
            {
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Single-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{3A413749-C918-4508-AAD9-78EF521A8E89}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Feature/ElisionFeatureTemplateAccordion/Base/_HeadingText/Data/HeadingText</description></item>
                /// </list>
                /// </summary>
                public const string HeadingText = "HeadingText";
            }
		}
    }
}
namespace Elision.Feature.Template.Accordion.SC.Integration
{
    public partial struct RulesFolders
    {
        /// <summary>
        /// <list type="table">
        ///     <item><term>ID:</term><description>{1D38B82B-6CFD-4F8F-8745-5364DA58107E}</description></item>
        ///     <item><term>Path:</term><description>/sitecore/system/Settings/Rules/Placeholder Settings/Rules</description></item>
        /// </list>
        /// </summary>
        public static readonly ID Placeholder_Settings = new ID("{1D38B82B-6CFD-4F8F-8745-5364DA58107E}");
    }
}
namespace Elision.Feature.Template.Accordion.SC.Integration
{
	public partial struct Templates
    {
        /// <summary>
        /// <list type="table">
        ///     <item><term>Template ID:</term><description>{2947978B-EB2D-4EEC-8C1C-198D1C23CB2B}</description></item>
        ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Feature/ElisionFeatureTemplateAccordion/Components/AccordionSection</description></item>
        /// </list>
        /// </summary>
        public struct AccordionSection
        {
            public static readonly ID TemplateId = new ID("{2947978B-EB2D-4EEC-8C1C-198D1C23CB2B}");
            public const string Name = "AccordionSection";

            public struct FieldIds
            {
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Single-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{3A413749-C918-4508-AAD9-78EF521A8E89}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Feature/ElisionFeatureTemplateAccordion/Base/_HeadingText/Data/HeadingText</description></item>
                /// </list>
                /// <para>This is an inherited template field</para>
                /// </summary>
                public static readonly ID HeadingText = new ID("{3A413749-C918-4508-AAD9-78EF521A8E89}");
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Rich Text</description></item>
                ///     <item><term>Field ID:</term><description>{AE9BA160-3E55-4F25-A514-EFE58728488F}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Feature/ElisionFeatureTemplateAccordion/Base/_Text/Data/Text</description></item>
                /// </list>
                /// <para>This is an inherited template field</para>
                /// </summary>
                public static readonly ID Text = new ID("{AE9BA160-3E55-4F25-A514-EFE58728488F}");
            }

            public struct FieldNames
            {
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Single-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{3A413749-C918-4508-AAD9-78EF521A8E89}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Feature/ElisionFeatureTemplateAccordion/Base/_HeadingText/Data/HeadingText</description></item>
                /// </list>
                /// <para>This is an inherited template field</para>
                /// </summary>
                public const string HeadingText = "HeadingText";
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Rich Text</description></item>
                ///     <item><term>Field ID:</term><description>{AE9BA160-3E55-4F25-A514-EFE58728488F}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Feature/ElisionFeatureTemplateAccordion/Base/_Text/Data/Text</description></item>
                /// </list>
                /// <para>This is an inherited template field</para>
                /// </summary>
                public const string Text = "Text";
            }
		}
    }
}
namespace Elision.Feature.Template.Accordion.SC.Integration
{
    public partial struct Renderings
    {
        public partial struct Organization
        {
            /// <summary>
            /// <list type="table">
            ///     <item><term>Rendering ID:</term><description>{7BB276D5-0008-47C7-8395-4730CEFF620D}</description></item>
            ///     <item><term>Path:</term><description>/sitecore/layout/Renderings/Elision/Feature/ElisionFeatureTemplateAccordion/Organization/Accordion</description></item>
            /// </list>
            /// </summary>
            public static readonly ID Accordion = new ID("{7BB276D5-0008-47C7-8395-4730CEFF620D}");
        }
    }
}
namespace Elision.Feature.Template.Accordion.SC.Integration
{
    public partial struct Renderings
    {
        public partial struct Accordion
        {
            /// <summary>
            /// The Accordion Section rendering.
            /// <list type="table">
            ///     <item><term>Rendering ID:</term><description>{88EB60A3-77C0-43B1-A6A6-C9F2470AA819}</description></item>
            ///     <item><term>Path:</term><description>/sitecore/layout/Renderings/Elision/Feature/ElisionFeatureTemplateAccordion/Organization/Accordion/Accordion Section</description></item>
            /// </list>
            /// </summary>
            public static readonly ID Accordion_Section = new ID("{88EB60A3-77C0-43B1-A6A6-C9F2470AA819}");
        }
    }
}
namespace Elision.Feature.Template.Accordion.SC.Integration
{
	public partial struct Templates
    {
        /// <summary>
        /// <list type="table">
        ///     <item><term>Template ID:</term><description>{9A3EA90B-1D8E-4E84-ACBC-9A7BEA167181}</description></item>
        ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Feature/ElisionFeatureTemplateAccordion/Base/_Text</description></item>
        /// </list>
        /// </summary>
        public struct _Text
        {
            public static readonly ID TemplateId = new ID("{9A3EA90B-1D8E-4E84-ACBC-9A7BEA167181}");
            public const string Name = "_Text";

            public struct FieldIds
            {
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Rich Text</description></item>
                ///     <item><term>Field ID:</term><description>{AE9BA160-3E55-4F25-A514-EFE58728488F}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Feature/ElisionFeatureTemplateAccordion/Base/_Text/Data/Text</description></item>
                /// </list>
                /// </summary>
                public static readonly ID Text = new ID("{AE9BA160-3E55-4F25-A514-EFE58728488F}");
            }

            public struct FieldNames
            {
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Rich Text</description></item>
                ///     <item><term>Field ID:</term><description>{AE9BA160-3E55-4F25-A514-EFE58728488F}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Feature/ElisionFeatureTemplateAccordion/Base/_Text/Data/Text</description></item>
                /// </list>
                /// </summary>
                public const string Text = "Text";
            }
		}
    }
}
